drivendataorg/concept-to-clinic

- prediction/requirements/base.txt
- prediction/src/preprocess/errors.py
- prediction/src/preprocess/load_dicom.py
- prediction/src/tests/test_load_dicom.py
This pull request adds the `load_dicom`-function into `./prediction/src/preprocess` that allows to load a DICOM-series in at a given folder path to be loaded into memory as a numpy-array using the `pydicom` and `dicom_numpy`-packages. The function also reraises exceptions from `pydicom` and `dicom_numpy` in case of corrupt DICOM-files or raises a `EmptyDicomSeriesException` implemented in `./prediction/src/preprocess.errors.py` if the give folder does not contain `*.dcm`-files. More extensive error handling might be necessary in later development stages.
Issue #12 
The change allows loading of DICOM-image series into memory for further processing.
Unittests using `pytest` were added at `./prediction/src/tests/test_load_dicom.py`. The tests assure that files are read correctly by `pydicom` …
> Implemented function to load a dicom series into memory as a numpy-array

- docs/design-doc.md
Changed headings on the "Jobs to be done" documentation page so that the heading links do not collide. Heading links are generated from the text of the headings, so having the same heading text on the same page causes issues. This seems to be the simplest solution.
I initially tried looking for other solutions, like `:ref:`, but the markdown to RST parser generates links automatically from the text with no obvious way to override.
Since the TOC is auto-generated using these heading links, it also becomes an issue when trying to link from the navigation pane to any `:ref` links on the page. Could manually create the TOC and navigation but would be tedious to update in the future.
Also tried enabling `autostructify` and trying to use the references in native RST embedded using `eval_rst` …
> Fix heading links in 'Jobs to be done' documentation page

- interface/backend/static/tests.py
Fixed a failing test
Initially, the test asserted existence for `Hello` text from the response. This text was not available or of use as of making this PR. The `index.html` template has a constant structure with `<title>Concept to Clinic<\title>` tag text . In addition, serving the `index.html` template should resolve a status 200 OK which is better for checking if the template was loaded.
Fixes #7 
This will make the tests in the `interface` app pass for `master` branch.
In the development setup using docker. Run:
`sh tests/test_docker.sh`
All tests should pass
> Fix failing static.SmokeTest.test_landing test 

- .githook-pre-commit
- docs/developing-locally-docker.md
I have implemented a githook-pre-commit file that has the `flake8` commands for styling and the command to run tests in the docker containers locally.
It meets requirements for #42 
This change will allow developers to run flake8 and tests before creating a commit. Flake8 command currently runs on uncommitted and staged python files with changes. This reduces the number of files that will be checked against before a commit. In case of project-wide checks, it could be done at CI level.
Documentation on how to set this up locally has also been included.
* Remove any existing `pre-commit` files in `.git/hooks` folder i.e. `rm .git/hooks/pre-commit`
* Copy the .githooks-pre-commit file into `.git/hooks/` as `pre-commit`
* Make it executable using `chmod +x .git/hooks/pre-commit`
* Run …
> Add default githooks for tests and flake8

- README.md
Changed link to point to Docker setup instructions, added another link to the main developer documentation page.
Fixes #46.
Documentation fix.
Tested the new links on the rendered MD page.
> Fix incorrect developer documentation link in the README

- docs/contribute.md
I added some details on how to clone the repo using LFS, how to track files and how to remove files from the Git history.
This should implement #16 
If possible, people should use Git LFS for big files so the repository size does not exceed the quota.
I checked out #55 and altered the documentation on that branch to directly see the compiled documentation on my computer.
> Add details on how to use Git LFS to the documentation

- prediction/src/tests/test_endpoints.py
- prediction/src/views.py
This is a very simple fix, I simply changed the endpoint to return the *docstring* of the selected `predict` function. Personally, I think this is the best way to keep it "self-documenting" and keeping the description in one place only. Let me know if you have problems with this approach.
Also, I added an `__init__.py` file to the `algorithms` folder to make it a valid Python package.
#10 
Modified the `test_endpoint_documentation` test to make sure that calls return the appropriate docstring.
> Self-documenting endpoint

- prediction/src/algorithms/segment/trained_model.py
- prediction/src/tests/test_endpoints.py
- prediction/src/views.py
To solve issue #14, I went with simply modifying the output of `/segment/predict/` to a dictionary of the format:
```python
{'binary_mask_path': str,
'volumes': list[float]}
```
For Issue #14 
I changed the unit test for `test_segment` to test for the new format of the returned response.
> Adjust segment model interface to return volumes of each nodule

- .gitignore
- docs/Makefile
- docs/conf.py
- docs/index.rst
This pull request should add the ability to auto-generate code documentation based on Google-styled docstrings. 
This should solve #8 
Instead of manually adapting the documentation to the written code and its docstrings, we can now auto-generate the Sphinx documentation based on the docstrings in the code.
1. I merged my code into #55 (so it's easier for me to update the documentation :-) )
2. I started docker-compose
3. I saw the auto-summaries of all modules, classes and methods that have proper docstrings
4. To confirm that it really supports Google-style docstrings, I downloaded [this](http://www.sphinx-doc.org/en/stable/ext/example_google.html) sample code having lots of Google-docstrings
5. I restarted docker-compose
6. I confirmed that the docstrings of that file were added to the …
> #8 Add Sphinx Autodoc 

- interface/backend/static/urls.py
- interface/backend/static/views.py
- interface/config/settings/base.py
- interface/frontend/index.html
- local.yml
For debugging purposes it would be really nice to see in the top right corner which version is currently used. The version is the short SHA-1 commit hash.
Since I didn't want to add the whole `.git` directory to the Docker container, I just added `.git/logs/HEAD` as a volume which contains historical information about branch changes etc. 
This should solve #29 
The big advantage is that by just adding `HEAD` we don't have the full Git history in our container. Furthermore, every time we switch branches or commit, the `HEAD` file is synchronized with the container (as well as the Docker volumes). In the container, a Django view parses the short current commit hash out of that file and displays it. This way, when switching branches not only the code in the container is synchronized with the …
> #29 Show current Git version in top-level navigation

- .gitignore
- docs/Makefile
- docs/apidoc_interface/backend.api.rst
- docs/apidoc_interface/backend.cases.migrations.rst
- docs/apidoc_interface/backend.cases.rst
- docs/apidoc_interface/backend.images.migrations.rst
- docs/apidoc_interface/backend.images.rst
- docs/apidoc_interface/backend.rst
- docs/apidoc_interface/backend.static.rst
- docs/apidoc_interface/config.rst
- docs/apidoc_interface/config.settings.rst
- docs/apidoc_interface/manage.rst
- docs/apidoc_interface/modules.rst
- docs/apidoc_prediction/config.rst
- docs/apidoc_prediction/modules.rst
- docs/apidoc_prediction/src.algorithms.classify.rst
- docs/apidoc_prediction/src.algorithms.identify.rst
- docs/apidoc_prediction/src.algorithms.rst
- docs/apidoc_prediction/src.algorithms.segment.rst
- docs/apidoc_prediction/src.preprocess.rst
- docs/apidoc_prediction/src.rst
- docs/apidoc_prediction/src.tests.rst
- docs/index.rst
I added the auto-generated .rst files.
I removed `_apidoc_{prediction, interface}` from `.gitignore`, removed the underscore prefix and updated the references to the folders accordingly.
This should fix #79 
This should enable us to see the code documentation on http://concept-to-clinic.readthedocs.io/en/latest/ as well.
I ran  
`$ docs: make html && python -m http.server`
and saw the documentation on `localhost:8000`.
To test it on readthedocs as well, I created my own account and deployed the current master and this branch. With the [master](http://concept2clinic.readthedocs.io/en/master/) version you can see that there is no code documentation section. In the documentation for [this branch](http://concept2clinic.readthedocs.io/en/latest/), there is one.
> #79 Fix: Code Documentation is not being displayed

- .gitattributes
- docs/configure git-lfs.md
This is a documentation about the installation of git lifs in the current project and how it can be used. I have referred to the git tutorials for the different platforms on ehich git lfs can be installed and can be used to refer the large images in a different server without they been present in the code repo.
All the diff platforms Mac, Windiws, Linux, Rhel/CentOS, Debian are mentioned.
The image files which are referred are present in the .gitattributes file as below:
_prediction/src/algorithms/identify/assets/ filter=lfs diff=lfs merge=lfs -text
prediction/src/algorithms/classify/assets/ filter=lfs diff=lfs merge=lfs -text
prediction/src/algorithms/segment/assets/ filter=lfs diff=lfs merge=lfs -text
*.dcm filter=lfs diff=lfs merge=lfs -text
prediction/src/algorithms/classify/assets/* …
> doc for git lfs

- docs/Makefile
- docs/apidoc_interface/backend.api.rst
- docs/apidoc_interface/backend.cases.migrations.rst
- docs/apidoc_interface/backend.cases.rst
- docs/apidoc_interface/backend.images.migrations.rst
- docs/apidoc_interface/backend.images.rst
- docs/apidoc_interface/backend.static.rst
- docs/apidoc_interface/config.rst
- docs/apidoc_interface/config.settings.rst
- docs/apidoc_prediction/src.algorithms.classify.rst
- docs/apidoc_prediction/src.algorithms.identify.rst
- docs/apidoc_prediction/src.algorithms.rst
- docs/apidoc_prediction/src.algorithms.segment.rst
- docs/apidoc_prediction/src.preprocess.rst
- docs/apidoc_prediction/src.rst
- docs/apidoc_prediction/src.tests.rst
- docs/how-to-edit-this-docs.md
- docs/index.rst
- local.yml
- prediction/requirements/local.txt
- prediction/src/factory.py
- tests/test_docker.sh
I have bootstrapped the steps needed for local installation, building and editing of the documentation for this project.
This addresses the issue #41 
This change enables developers to be able to edit the documentation locally. Since docker is the official development configuration, I used it to create the application and link it to the current development.
Locally, when you run
`$ docker-compose -f local.yml up`
the documentation application will be running on (http://localhost:8002/)[http://localhost:8002/]
> Document how to update documentation

- prediction/src/algorithms/classify/trained_model.py
- prediction/src/algorithms/identify/trained_model.py
- prediction/src/algorithms/segment/trained_model.py
- prediction/src/tests/test_endpoints.py
- prediction/src/views.py
Prediction API now returns message specifying if a needed parameter is not
passed to the prediction algorithm, and passes error messages that occur within
the prediction algorithm.
The API passes an error message if a non-existent algorithm is selected, as before. The API now also passes an error message if a necessary parameter to the algorithm is missing, specifying the algorithm chosen and the required parameter.  All other errors (e.g., bad DICOM file path) should be caught within the prediction algorithm, and these messages are caught and passed through the API.
Fixes issue #11 
These changes are tested through additional tests in test_endpoints.py. To properly test the response to bad DICOM paths, I modified the "predict" functions of the three "trained_model.py" modules to load the …
> Improve error handling in prediction API

- docs/developing-locally-docker.md
The Docker will not run on Windows 7 but the error is not informative and someone(like me) could spend lots of time trying to find what is the issue and how to solve it.
Windows 7 users should use **Docker Toolbox** instead of Docker. Docker installation will fail with not informative message _LightWeightInstaller has stopped working_. After enabling assembly binding logging (FusionLog) one may find, that the issue is `PresentationFramework.Aero2.dll` can't be found. But instead of trying to solve the issue, one should just use **Docker Toolbox**.
> Added a note about Docker Toolbox for Windows 7 users

- docs/templates/algorithm_doc_template.md
I added a first draft of a template for documenting candidates of prediction algorithms that could be included into this project. 
Issue #58 
The template contains the following sections:
- A short summary
- Source of the algorithm
- License
- Prerequisites
- Description of the algorithm design
- Reference/User instructions to the trained model
- Model performance
- Use cases
- Changes that are needed for adaptation into this project
- Misc. comments
- References
The markdown is displayed correctly in PyCharm.
This is just a first draft and I encourage everybody to comment or commit possible improvements to this pull request.
> Added first draft of template for documentation of prediction algorithm

- docs/apidoc_interface/backend.static.rst
- interface/assets/css/project.css
- interface/backend/api/urls.py
- interface/backend/api/views.py
- interface/backend/static/tests.py
- interface/backend/static/urls.py
- interface/frontend/annotate_and_segment.html
- interface/frontend/base.html
- interface/frontend/detect_and_select.html
- interface/frontend/open_image.html
- interface/frontend/report_and_export.html
- interface/frontend/shared/tabs.html
- tests/test_docker.sh
This should add an "accordion" view that shows the candidate nodules for a selected image. The candidate fields `lidc_max_sensitiv, convnet_vgg, convnett_vgg_lidc, Slice` still need to be implemented in the back-end.
I added the front-end Vue.js implementation to display candidate nodules of an image based on the current API.
This addresses #35 .
The doctor should be able to quickly get an overview of candidate nodules including their probability of being cancer.
I created two dummy candidates by letting the API return
```
[{		
"centroid": {		
"x": 54,		
"y": 78,		
"z": 23,		
"series": 0		
},		
"probability_concerning": 0.94,		
"case": 1		
},		
{		
"centroid": {		
"x": 1,		
"y": 2,		
"z": 3,		
"series": 1		
},		
"probability_concerning": 0.94,		
"case": 1		
}]
```
The outcome was
> #35 Show list of candidates nodules

- .gitignore
- interface/backend/api/urls.py
- interface/backend/api/views.py
New API for direcotory listing in homepage as described in #77 
Introducing new API endpoint which will be used to retrieve images from data directory.
See issue #77 
This modification will effect homepage initial dataload. Implementation of the API is yet to be made.
> New API endpoint to fetch dataset directory

- README.md
This should update the Travis badge in the readme to reflect this repository's current build state.
This addresses #103
> #103 Adapt Travis badge

- docs/_static/c2c_custom.css
- docs/project-structure.md
(resubmission of PR#64 - couldn't just reopen it cause I deleted the old fork and there was some weird merging thing going on)
Hi, I've added links for everything below. There weren't any explicit instructions on where to link so I just linked to the documentation home for the most part. On some occasions, I would link to a specific part of the documentation (Django Migrations, Docker Containers etc.):
* Docker
* docker-compose
* sphinx
* Django
* Django Rest Framework
* Vue.js
* Django database migrations
* requirements.txt
* DICOM
* git-lfs
* Flask
* flake8
Links not added (there didn't seem to be any place to put them, advice?):
* pip
* pytest
Oh yea, while I was looking through it I found some minor typos so I also added those changes.
#15 - Add links to the project structure …
> #15 - Add links to the project structure documentation

- docs/algorithm_de_wit.md
I added an initial documentation of the Julian de Wit algorithm. The algorithm output was ensembled with the results of the [Daniel Hammack algorithm](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/docs/algorithm_hammack.md).
This pull request addresses #20 
> #20 Document the Julian de Wit algorithm

- interface/backend/api/tests.py
- interface/backend/api/views.py
- interface/config/settings/base.py
Return simple 2 level directory listing from `/images/available` api
`/images/available` will return directory and files in alphanumerically sequential order
issue #31 
Current API return only emplty list.
Unit test added to test http response. We have tested against the test image direcotry available at `/images/LIDC-IDRI-0001/1.3.6.1.4.1.14519.5.2.1.6279.6001.298806137288633453246975630178` which return following direcotry list in alphabetical order
In Index Page:
API returns:
> #31 Directory List of Datasource

- docs/apidoc_interface/backend.rst
- interface/backend/api/tests.py
- interface/backend/api/views.py
I replaced JsonResponses by Responses which follows the DRF idioms.
This addresses #111 .
I added two tests so all functions, that previously used JsonResonses, are tested whether they still return valid JSON.
> #111 Replace JsonResponses by Responses

- interface/backend/api/serializers.py
- interface/backend/api/urls.py
- interface/backend/api/views.py
- interface/backend/cases/models.py
- interface/backend/cases/tests.py
- interface/backend/images/models.py
This PR is based on and blocked by #93 (because this already adds a proper creation of candidates). To see the raw changes this PR wants to add, please see [here](https://github.com/WGierke/concept-to-clinic/compare/36_accept_reject_candidates...WGierke:30_case_json_report).
Now, a JSON report can be generated for a case that includes the patient id, candidates, nodules, etc.
I fixed the creation of nodules, added the JSON report and wrote a test for that.
This addresses #30.
This should summarize the data of a case and help debugging.
I wrote a test which adds a case with image series, candidates and nodules and which tests for a proper report.
> #30 Add JSON case reports

- .gitattributes
- prediction/requirements/base.txt
- prediction/src/algorithms/segment/assets/test_mask.npy
- prediction/src/algorithms/segment/trained_model.py
- prediction/src/preprocess/load_dicom.py
- prediction/src/tests/test_calculate_volume.py
- prediction/src/tests/test_load_dicom.py
This method computes the volume of connected components placed at the specified centroids, via connected component analysis using `scipy.ndimage.label`. The `voxel_shape` parameter has added to the function in order to derive units of measure. 
Calculate tumor volume from pixel masks [#13](https://github.com/concept-to-clinic/concept-to-clinic/issues/13) 
The unit test for `calculate_volume` has been added to test for the volume calculation over the different mask instances. During the testing, another issue has acquired at `test_segment`, which was related to the meaningless `segment_path`. Hence the changes were also added to the `segment.predict` function.
> Calculate tumor volume

- prediction/src/algorithms/classify/__init__.py
I added the missing content of `__init__.py`.
This addresses #123 .
I rebuilt and fired up `docker-compose` again, which showed the correct API landing page.
> #123 Fix AttributeError: module 'src.algorithms.classify' has no attribute

- .github/ISSUE_TEMPLATE.md
I replaced `local.py` with `local.yml` in the issue template. This addresses #127 .
> #127: Fix typo in issue template: local.py -> local.yml

- compose/documentation/Dockerfile-dev
- docs/apidoc_interface/backend.static.rst
- docs/apidoc_prediction/src.tests.rst
- docs/conf.py
- interface/backend/api/views.py
- local.yml
Turned out to be pretty finicky to fix, Sphinx (apidoc) and Django can be a pain to get working together. Changes made:
- Re-add the two Docker images (`compile_docs` and `documentation`). I've setup a new Docker file for both of these images that uses the requirements from the interface and prediction modules as well as the documentation-specific requirement file.
- Add some required additional environment variables to allow Django to at least be importable for Sphinx's apidoc. I re-use the `compose/interface/entrypoint.sh` file from the `interface` module to setup the `DATABASE_URL` env variable that's required for django, before running the Sphinx makefile. Currently a blank string works for the URL, but I'm future-proofing in case a real URL becomes necessary for Sphinx in the future. …
> Fix documentation compilation

- prediction/src/preprocess/crop_patches.py
- prediction/src/preprocess/generators.py
- prediction/src/preprocess/load_ct.py
- prediction/src/preprocess/preprocess_ct.py
- prediction/src/tests/test_crop_patches.py
- prediction/src/tests/test_generators.py
- prediction/src/tests/test_load_ct.py
- prediction/src/tests/test_preprocess_dicom.py
The data augmentation process is a very common stage for a plenty of approaches in machine learning, especially in computer vision. The majority of the solutions of the #1, #2, #3 has the similar augmentation pipeline (e.g. [grt123](https://github.com/WGierke/concept-to-clinic/blob/457b7a7528fda28ed556d234135d48595eaa13ce/docs/algorithm_grt123.md), [Therapixel](https://github.com/WGierke/concept-to-clinic/blob/d9a20abfb817642ba6d98e403ed6659446125853/docs/algorithm_therapixel.md), [Daniel Hammack](https://github.com/WGierke/concept-to-clinic/blob/a47d8f28435f612d93a8eee694ac5c82500e710f/docs/algorithm_hammack.md), etc.). The aforementioned pipeline mainly consists of Hounsfield scaling, lungs segmentation (#120), CT re-orientation and a batch of trivial, yet resource consumptive spacial …
> Data Generator

- docs/algorithm_owkin.md
I added an initial documentation of the Owkin algorithm. The algorithm scored 10th place during the DSB 2017.
Unfortunately, there is no technical report or blog post about the approach so far.
Thus, I had to derive the algorithm design from the source code and black-box models only, which resulted in a shorter documentation than for other algorithms.
This pull request addresses #28 
> #28 Document the Owkin algorithm

- .gitattributes
- compose/prediction/Dockerfile-dev
- prediction/requirements/base.txt
- prediction/src/algorithms/classify/assets/gtr123_model.ckpt
- prediction/src/algorithms/classify/src/gtr123_model.py
- prediction/src/algorithms/classify/trained_model.py
- prediction/src/algorithms/identify/assets/dsb2017_detector.ckpt
- prediction/src/algorithms/identify/src/gtr123_model.py
- prediction/src/algorithms/identify/trained_model.py
- prediction/src/preprocess/extract_lungs.py
- prediction/src/preprocess/gtr123_preprocess.py
- prediction/src/tests/__init__.py
- prediction/src/tests/test_classify_trained_model_predict.py
- prediction/src/tests/test_endpoints.py
- prediction/src/tests/test_identify_trained_model_predict.py
This pull request implements the grt123 identification algorithm.
It is based on PyTorch, which currently conflicts with Tensorflow, so the pull request also disables the Keras import. 
While the algorithm is quite fast on GPU, it is painfully slow (but working) on the CPU due to a bug in PyTorch. The bug is fixed in the PyTorch development branch, but the next release is about 2 months off. 
https://github.com/concept-to-clinic/concept-to-clinic/issues/4
https://github.com/concept-to-clinic/concept-to-clinic/issues/1
This Pull request implements  part of the prediction service (https://concept-to-clinic.readthedocs.io/en/latest/design-doc.html#detect-prediction-service) 
The algorithm has largely been tested by manually confirming about 5 random LUNA2016 datasets - as the loaded model …
> Converted Team 'grt123' identification and classification algorithms

- prediction/src/algorithms/segment/src/evaluate.py
- prediction/src/tests/test_segment_evaluate.py
The followed measures and distances have been provided: sensitivity, specificity, [Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient), the [analogy to Dice coefficient](https://github.com/jocicmarko/ultrasound-nerve-segmentation/blob/master/train.py) and [Hausdorff distance](https://en.wikipedia.org/wiki/Hausdorff_distance). This metrics may be employed for segmentation evaluation of both: lungs and nodules. 
This address #143
Unit tests were created for each metric and ran over block-typed input.
> #143 Segmentation Evaluation

- local.yml
I fixed the RuntimeError described in #152 by setting the appropriate variables.
> #152 Fix RuntimeError

- .dockerignore
- interface/frontend/build/dev-server.js
- interface/frontend/package.json
- interface/frontend/src/components/Candidate.vue
- interface/frontend/src/components/CandidateList.vue
- interface/frontend/src/components/ImageSeries.vue
- interface/frontend/src/components/Nodule.vue
- interface/frontend/src/components/NoduleList.vue
- interface/frontend/src/main.js
as described in #162 with node 8 an error is thrown after starting the vuejs dev-server. This is caused by the dev-server trying to start a browser window inside the docker container which leads to a rejected promise.
This PR fixes this issues. Additionally it improves the following:
* remove VueResource (we use axios for http requests as i understood, therefore VueResource is not needed anymore)
* fix current axios requests to also handle rejected promises correctly with catch statements
* add correct node_modules path to .dockerignore
> Fixing error unhandled promise rejection #162, removing VueResource

- interface/config/urls.py
This `http://0.0.0.0:8000/` route to a page listing all the available routes.
`http://0.0.0.0:8000/` redirect to `/api/routes` which in turn will return the dictionary of available links. 
This addresses #157.
Currently, navigating to `http://0.0.0.0:8000/` returns a 404 error.
The API and JSON response:
> #157 Listed available routes

- interface/backend/api/views.py
- interface/frontend/package.json
- interface/frontend/src/components/ImageSeries.vue
- interface/frontend/src/main.js
Filtering out the hidden files from the Vue frontend.
During working over this PR I've stumbled upon the unexpectable behaviour in `src/components/ImageSeries.vue`:
```javascript
[Vue warn]: Error in render: "TypeError: _vm.availableSeries is undefined"
found in
---> <ImageSeries> at src/components/ImageSeries.vue
<OpenImage> at src/views/OpenImage.vue
<App> at src/App.vue
<Root>
```
Though the response of the `/api/images/available` was sustainable and in a proper format. It took a while from me to figure out that this behaviour was introduced by the PR #171, specifically by the exchange `$http` on `$axios` ([1](https://github.com/concept-to-clinic/concept-to-clinic/pull/171/files?diff=unified#diff-ff7a640b74e49c1a5b1dbb329689f4b7R102) and …
> #158 Hide hidden files

- interface/frontend/src/assets/css/project.css
> We want some more room to work with
This address #180
> #180 CSS adjust margin

- interface/backend/api/serializers.py
- interface/frontend/package.json
- interface/frontend/src/components/open-image/ImageSeries.vue
- interface/frontend/src/components/open-image/OpenDICOM.vue
- interface/frontend/src/components/open-image/TreeView.vue
- interface/frontend/src/main.js
- interface/frontend/src/views/OpenImage.vue
The ability to show DICOM images is one of the most important parts for this project. There are existing libraries that provide a way to show DICOM images that can help with this task. It were two main candidates with proper library to choose from: [ivmartel](https://github.com/ivmartel) and [chafey](https://github.com/chafey). The decision was made to use the [cornerstone](https://github.com/chafey/cornerstone) library for the reason that it flexible and can provide the project with ability to show images in an interactive way. It is also was much easier to use with VueJS than its competitor.
Two main difficulties were met during the work on this issue. The first one was the problem with pixelData serialization. It took some time before a good solution was found.
The second problem was …
> #179 DICOM image viewer

- compose/base/Dockerfile-dev
- compose/documentation/Dockerfile-dev
- compose/interface/Dockerfile-dev-api
- compose/prediction/Dockerfile-dev
- interface/requirements/base.txt
- local.yml
First, a base image is built that installs all needed pip requirements. The docker containers, that need parts of the requirements (prediction, interface and documentation services), then are built on top of that base image. Thus, building the documentation service doesn't require to install all pip requirements again resulting in a great speed-up of the container building.
This addresses #159 
`docker-compose -f local.yml build && docker-compose -f local.yml up` builds all containers properly and fires them up.
PS: Accelerated the build time on Travis from μ=23.5min ± 2.2 min (measured on the last 25 builds) to 18 min (first successful build of this branch) :tada: The time it takes to build the services locally should thus also greatly be decreased.
> #159 Docker: Reuse Caches

- compose/base/Dockerfile-dev
Remove all __pycache__ files when you run `docker-compose -f local.yml build prediction`.
Added a one-line code in Docker file referenced at #161  by @reubano 
fixes #161 
Old __pycache__ files can interfere with proper running of docker-compose -f local.yml build and may even cause the following error:
```
import file mismatch:
imported module 'app.src.tests.test_load_ct' has this __file__ attribute:
/Volumes/Nahla/alcf/prediction/src/tests/test_load_ct.py
which is not the same as the test file we want to collect:
/app/src/tests/test_load_ct.py
```
There should be a convenient script that can be run to remove all __pycache__ files.
Run build several times without any error.
> #161 Remove pycache directories files on build

- prediction/src/algorithms/identify/src/gtr123_model.py
- prediction/src/algorithms/identify/trained_model.py
Fixed #191 (Nodule identification doesn't work)
- [fixing the issue](https://github.com/concept-to-clinic/concept-to-clinic/pull/213/commits/43a55868a71ac69833033a561840e1a030718d6a)
- [adding back file name validation](https://github.com/concept-to-clinic/concept-to-clinic/pull/213/commits/807300119c990ac3c5b235f80660367e2df43fa1)
The problem was - passing image object to `gtr123_model.predict` method, when this method expects a path to a DICOM image.
I checked that it starts with right input, but can't do the full run because of *not enough memory* error.
> Fixed nodule identification

- local.yml
Closes the issue #203 that threw an error whe you visit the http://localhost:8001/ endpoint in the prediction application.
Using `python -m flask run ...` to start server. More info in docs [here](http://flask.pocoo.org/docs/0.11/cli/#basic-usage)
This closes issue #203 
- `docker-compose -f local.yml up`
- visit [http://localhost:8001/](http://localhost:8001)
- Should load the home page
This removes the traceback error when you visit [http://localhost:8001/](http://localhost:8001)
When you visit [http://localhost:8001/](http://localhost:8001) you should not get an error
> #203 Fix error showing no module named 'src' found.

- interface/frontend/package.json
- interface/frontend/src/components/open-image/ImageSeries.vue
- interface/frontend/src/components/open-image/OpenDICOM.vue
- interface/frontend/src/components/open-image/TreeView.vue
Manipulations over DICOM such as `scroll`, `window width` / `window centre`, etc. series were requested by both #148 and #149. Were implemented by [`cornerstoneTools`](https://github.com/chafey/cornerstoneTools). It took a while to distinguish sustainable versions, compatible with this project:
```javascript
"cornerstone-core": " 0.13.0",
"cornerstone-tools": " 0.10.0",
"jquery": "^3.2.1"
```
I'd like to separate them from drawing features and made them part of [`OpenDICOM`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:148_detect_and_select?expand=1#diff-70d179422138a3042c2135a282065626), still any suggestions are highly appreciated!
In this PR `scroll`, `window width` / `window centre` DICOM manipulators were implemented.
This partially addresses #148 …
> #148 Manipulations with DICOM vue

- local.yml
This assigns a static name to the generated  `base` image such that docker still works if your directory is named something else than "concept-to-clinic". This addresses #222 .
> #222 Fix docker-compose build error

- interface/backend/api/views.py
- interface/frontend/build/dev-server.js
- interface/frontend/src/components/annotate-and-segment/NoduleList.vue
- interface/frontend/src/components/detect-and-select/CandidateList.vue
- interface/frontend/src/components/open-image/ImageSeries.vue
- interface/frontend/src/components/open-image/OpenDICOM.vue
- interface/frontend/src/components/open-image/TreeView.vue
- interface/frontend/src/components/report-and-export/RSNAStandardTemplate.vue
Loading [http://localhost:8080/](http://localhost:8080) throws an `IsADirectoryError: [Errno 21] Is a directory: '/'`
The endpoint is called every time the front end loads. Since the `dicom.readfile()` method is an IO op, I do a `try/except` to catch the `IOError` 21. As it is, this error is only anticipated on page load because there's no default path to a dicom file. I return an 'empty' response back so that the error is handled on the server-side and presents the client side an opportunity to handle it too.
`Cornerstone` throws errors if handed empty fields on the front end. Since the functions trigger calls to the server endpoint on load (I am assuming this is because of the `async/await` computed functions -- please correct my reasoning here if I'm wrong) and has nothing to display, …
> #206 IsADirectoryError fix

- interface/backend/api/tests.py
- interface/backend/api/views.py
Now each `[Model]ViewSet` will inherit from `ViewSetBase` and that base view class has `get_serializer_context` method overridden to set `'request': None` for the serialization context.
After this change serialized entities have relative URLs instead of absolute and it makes them usable from the Vue.js application. Problem with absolute URLs - interface API is hosted on different port number then *Vue.js* and requests to that port number being blocked by browser because of CORS policy. Now the URLs are pointing to the same host and will be redirected by *Node.js* server.
Fix suggested by @isms when discussing #228
> Fixed interface API to return relative urls instead of absoulte

- .gitignore
- docs/apidoc_interface/interface_doc.rst
- docs/apidoc_prediction/prediction_doc.rst
- docs/conf.py
- docs/index.rst
Create new files to handle the index pages of the `prediction` and `interface` modules inside `docs`.
Generally, `sphinx-api` on these two modules auto generates the documentation. Ignore the previously generated `modules.rst` files because they're automatically generated and changes made to them are overridden.
Fixes issue #198.
Makes the cases of the `Code Documentation` titles begin with upper case.
- `docker-compose -f local.yml build && docker-compose -f local.yml up`
- Open [http://localhost:8002/](http://localhost:8002/)
- Titles in the section *Code Documention* should start with upper case
> #198: Update case of links in documentation sidebar

- interface/frontend/package.json
Because of [this bug](https://github.com/vuejs/vue/issues/7084) in version 2.4.2 of **Vue.js** the compilation of Vue app was broken. I have fixed it by updating the package.
> fixed Vue.js compilation error by updating Vue.js version

- .travis.yml
- tests/test_docker.sh
- tests/test_routes.py
I added a simple Python script that can test whether routes error. It is highly customizable (e.g. one could add to check for the occurrence of the word "error" or "exception" etc.).
This addresses #160 
Currently, the Travis test passes even if some routes are non-functional (like http://0.0.0.0:8001/).
It's currently not passing due to the unfixed issue #203 .
```bash
➜  concept-to-clinic git:(160_route_errors) ✗ bash tests/test_docker.sh
...
+ python tests/test_routes.py
http://localhost:8001/ returns 500
+ echo 'ERROR: test_routes did not pass. Check above for details.'
ERROR: test_routes did not pass. Check above for details.
+ exit 1
```
> #160 Add Route Testing

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates `PULL_REQUEST_TEMPLATE.md` to include various prediction algorithm metrics such as logloss and prediction time. View [formatted file](https://github.com/concept-to-clinic/concept-to-clinic/blob/630e1aeae7673b2bb0fc466c99f7612047438cf7/.github/PULL_REQUEST_TEMPLATE.md#metrics-if-appropriate).
This PR will allow us to evaluate current and future machine learning algorithms in a standardized and objective fashion.
- [ x ] I have signed the CLA; if other committers are in the commit history, they have signed the CLA as well
> Update PR TEMPLATE to include prediction algorithm metrics

- local.yml
- prediction/src/algorithms/segment/assets/lung-mask.npy
- prediction/src/tests/__init__.py
- prediction/src/tests/conftest.py
- prediction/src/tests/test_endpoints.py
- prediction/src/tests/test_identification.py
- prediction/src/tests/test_segmentation.py
- tests/test_docker.sh
We don't want to completely skip slow tests since this can hide bugs (e.g. #191). Instead, we want to start the slow tests but skip them after a specified period of time.
If the environment variable RUN_SLOW_TESTS is set to True, all tests should be run. Otherwise tests that exceed the time specified by the variable TESTS_TIMEOUT (default is 15 seconds) are skipped without causing an error.
This addresses #195 
It was necessary to create a new [hook](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...WGierke:195_stop_slow_tests?expand=1#diff-507495becfd1e874bad6e0b1cf4437b2R115) that checks whether a test should timeout, that kills the test when exceeding the timeout and then returns that the test is not failing (if the timeout is the only reason for the test exit). …
> #195 Stop slow tests after set period of time

- prediction/src/tests/conftest.py
This PR fixed the case that a `Termination` exception can be thrown in tests that should timeout.
This addresses #247 .
> #247 Only use TimeoutExit for timeouts

- interface/frontend/src/components/open-image/AreaSelect.vue
- interface/frontend/src/components/open-image/OpenDICOM.vue
Implemented Vue.js component for area selection based on [this project](https://github.com/neshte/jquery-canvas-area-draw). Did following updates:
- converted to Vue component
- get rid of jQuery dependency
- added ability to move entire area when `Shift` is pressed
Can be used as simple as this:
`<area-select @selection-changed="areaSelectChange" v-if="showAreaSelect" :selectedArea="currentArea"></area-select>`
#150
Since I used [this project](https://github.com/neshte/jquery-canvas-area-draw) as a starting point, should I include it's license in the code?
> implemented area select vue component for Segmentation page (#150)

- prediction/src/algorithms/identify/trained_model.py
- prediction/src/tests/test_identification.py
I fixed the identification of LUNA nodules as far as it gets on my machine. This means that currently all tests in `src/tests/test_identification.py` are failing for me since I don't have 21 GB of RAM (if RUN_SLOW_TESTS is set to true). Maybe someone else can execute them and send me tracebacks for further error investigation?
The problem was that sometimes the direct path to a MHD file was handed to the function instead of the path to the directory. The made changes should support now both alternatives.
This addresses #229 - identification test(s) should pass for luna scans.
I added the test given in #229 .
> #229 Fix identification on LUNA

- interface/backend/api/serializers.py
- interface/backend/api/urls.py
- interface/backend/api/views.py
- interface/frontend/src/components/detect-and-select/Candidate.vue
- interface/frontend/src/components/detect-and-select/CandidateList.vue
- interface/frontend/src/components/open-image/NoduleMarker.vue
- interface/frontend/src/components/open-image/OpenDICOM.vue
Implemented slice switching for candidate list, and a way for user to see when slice differs and attach the marker to current slice.
Following features has been implemented:
- switching the viewer to candidate's slice when selecting a candidate
- showing to user that marker is on an other slice
- clicking on a marker attaches it to current slice
On back-end I have added a method for loading candidates with cases and series. Series object will also have list of DICOM files in the folder saved in `uri` property.
It's an improvement of #148
[full size image](http://g.recordit.co/6AwCrut5WW.gif)
> Detect and select: attaching nodule centroid marker to current slice

- interface/frontend/build/dev-server.js
- interface/frontend/config/dev.env.js
- interface/frontend/src/components/AppNav.vue
- local.yml
Updates the short git hash that matches the current version of the code in the navbar
This allows the navbar to have the short version of the current commit hash from HEAD.
Fixes issue #244 
Get the hash of the latest commit as the display instead of a static value.
- Run `docker-compose -f local.yml build`
- Run `docker-compose -f local.yml up`
- View the application UI on [http://localhost:8080/#/](http://localhost:8080/#/)
- Open another terminal in the root of your project repo and run `git rev-parse --short HEAD`
- The hash on the top right side of the navbar should be the same to the value of the previous step
> #244 Update the version number in the navbar

- interface/backend/api/views.py
- interface/backend/cases/tests.py
- prediction/src/preprocess/load_ct.py
- prediction/src/tests/test_classification.py
There was no method implemented how to get the origin of a DICOM image series which resulted in an error. I initially set it to [0, 0, 0] but due to my lack of domain knowledge I don't know how to correctly calculate it from DICOM images. If you know the answer, feel free to comment :)
This references #229 - classification doesn't work on DICOM images.
I added the test given in #229
> #229 Fix Classification

- interface/backend/api/views.py
- interface/backend/cases/models.py
- interface/backend/cases/serializers.py
- interface/backend/images/models.py
- interface/backend/images/serializers.py
Move serializers in the `interface` app into a single file for each directory
Addresses issue #201 
Makes the app structure cleaner and concise
`interface.backend.cases` and `interface.backend.images` have a `serializers.py` file that holds all the respective serializers previously situated in their `models.py` files.
> Move all serializers into a single file in the same dir

- docs/algorithms/algorithm_DL_Munich.md
- docs/algorithms/algorithm_aidence.md
- docs/algorithms/algorithm_alex_andre_gilberto_shize.md
- docs/algorithms/algorithm_de_wit.md
- docs/algorithms/algorithm_deep_breath.md
- docs/algorithms/algorithm_grt123.md
- docs/algorithms/algorithm_hammack.md
- docs/algorithms/algorithm_mdai.md
- docs/algorithms/algorithm_owkin.md
- docs/algorithms/algorithm_qfpxfd.md
- docs/algorithms/algorithm_therapixel.md
- docs/algorithms/algorithms_doc.rst
- docs/conf.py
- docs/index.rst
- docs/templates/algorithm_doc_template.md
Add algorithm documentation pages to the docs table of contents
Addresses issue #258 
Adds algorithms documentation to the `toc tree`
- `docker-compose -f local.yml up`
- Navigate to [http://localhost:8002/](http://localhost:8002)
- The table of contents has the **Algorithms** section under **Code Documentation**
~~The algorithm doc files are in `markdown`. Most of them have tables and they're not well displayed on the pages (parsed as paragraphs 🙄 ). Some searching brought me across to this [stackoverflow answer](https://stackoverflow.com/a/44463828/4444629). Basically, to display the tables the best approach is to use `reST` mark up files.~~
> Updated documentation pages to the docs TOC

- interface/backend/api/tests.py
- interface/backend/cases/tests.py
Small fix of the candidates API tests based on this [discussion](https://github.com/concept-to-clinic/concept-to-clinic/pull/254#issuecomment-348448307).
> fixed candidate select\deselect API test

- prediction/src/preprocess/improved_lung_segmentation.py
- prediction/src/preprocess/load_ct.py
- prediction/src/preprocess/preprocess_ct.py
- prediction/src/tests/conftest.py
- prediction/src/tests/test_improved_segmentation.py
The threshold method consists of 4 steps: 
1) extraction of large airways;
2) segmentation of lung regions;
3) separation of the left and right lungs;
4) smoothing.
I have solved issue #138, there it was proposed to improve lung segmentation.
The algorithm includes errors in lung segmentation, which often occur at the borders of the lungs, when the contrast between the lung parenchyma and the surrounding tissue is low due to pathologic abnormalities that show up as dense regions. In normal lung anatomy, the shape of the costal lung surface is convex.
When an error occurs at the costal border, the surface is typically not convex anymore.
This problem was fixed with method, which was described in issue #138. Also bronchi and trachea were indicated and segmented in this method. 
I've tested …
> Improved lungs segmentation algorithm

- interface/frontend/src/components/common/NoduleMarker.vue
- interface/frontend/src/components/common/OpenDICOM.vue
Enabled window width and window center adjustment. Enabled zooming and panning. 
Updated the `NoduleMarker` component to rescale and move the marker accordingly.
Fixed bug - moving slider to cached slices didn't show those slices.
#240
> DICOM viewer: zoom and pan support

- prediction/src/preprocess/crop_patches.py
Bug fixed. When the length of the nodules list is more then 1 – prediction fails as follows:
```
~/concept-to-clinic/prediction/src/algorithms/classify/src/gtr123_model.py in predict(ct_path, nodule_list, model_path)
275     results = []
276 
--> 277     for nodule, (cropped_image, coords) in zip(nodule_list, patches):
278         cropped_image = Variable(torch.from_numpy(cropped_image[np.newaxis, np.newaxis]).float())
279         cropped_image.volatile = True
ValueError: too many values to unpack (expected 2)
```
More details [here](https://github.com/concept-to-clinic/concept-to-clinic/pull/272#issuecomment-355413434).
> fixed classification prediction for multiple nodules

- .gitignore
- prediction/src/algorithms/classify/src/gtr123_model.py
- prediction/src/algorithms/identify/src/gtr123_model.py
- prediction/src/preprocess/crop_patches.py
- prediction/src/preprocess/preprocess_ct.py
- prediction/src/tests/conftest.py
- prediction/src/tests/test_classification.py
- prediction/src/tests/test_cropping.py
- prediction/src/tests/test_grt123_preprocess.py
- prediction/src/tests/test_preprocess_dicom.py
We had a problem - the preprocessing is [zooming the image](https://github.com/concept-to-clinic/concept-to-clinic/blob/666fb1bf410cbd80eb7928d0e3c5f2433ad668a5/prediction/src/preprocess/preprocess_ct.py#L144). In other words, the pixel matrix is resized to real proportions. But coordinates we are using for prediction are not scaled accordingly and the actual patch we are making prediction on differs from the expected patch.
For example, the zooming factor for full LIDC-IDRI-0003 image is [2.5, 0.820312, 0.820312]. The prediction result for **coordinates of the real nodule** {'x': 367, 'y': 350, 'z': 72} is **0.0066**. As you can see, it's very low. But if you scale these coordinates by the current zooming factor ({'x': 301, 'y': 286, 'z': 180}) we will get much higher probability of …
> Fixed coordinates scaling for classification prediction

- prediction/requirements/local.txt
- tests/test_docker.sh
As discussed in #275, it would be helpful to generate a coverage report of the unit tests in which the total coverage and missing lines can be seen. This PR adds [Coverage.py](https://coverage.readthedocs.io/en/coverage-4.4.2/) which keeps track of which LOC haven't been tested after running the tests. It generates a `htmlcov` directory which includes the HTML files that should be served afterwards to correctly render the report. Examples of such reports for the current master are here: [prediction](https://wgierke.github.io/stuff/prediction/index.html), [interface](https://wgierke.github.io/stuff/interface/index.html).
To persist this report generated by Travis, the project manager need to [set up Travis artifacts](https://docs.travis-ci.com/user/uploading-artifacts/).
> Add Python Coverage Report

- prediction/src/views.py
While skimming through [code that still needs to be tested in the prediction service](https://wgierke.github.io/stuff/prediction/index.html), I noticed this line that prevented the file from being completely covered by tests. The reason was that the condition was never false since the `methods=['GET', 'POST']` parameter prevents any other request than a `POST` request from reaching this LOC.
> /<algorithm>/predict/: Only expect GET or POST requests

- prediction/src/evaluations/froc.py
This allows to compute [FROC](https://doi.org/10.1093/jicru/ndx009) and [CPM](https://doi.org/10.1109/TMI.2010.2072789) metrics with bootstrapping for the classification and detection tasks.
Free-Response Receiver Operating Characteristic ([FROC](https://doi.org/10.1093/jicru/ndx009)) and competition performance metric ([CPM](https://doi.org/10.1109/TMI.2010.2072789)). It computes an average of the seven sensitivities measured at several false positives per scan (FPPS) thresholds, more concretely, at each FPPS ∈ {0.125, 0.25, 0.5, 1, 2, 4, 8} true positive rate was computed. Mean of which forms the CPM as discussed in #271. 
This reference to the #271.
[CPM](https://doi.org/10.1109/TMI.2010.2072789) over 10-Fold cross validation:
| 0.125 | 0.25 | 0.5 | 1 | 2 | 4 | 8 | Score …
> #271 LUNA16 evaluation

- prediction/requirements/base.txt
- prediction/src/algorithms/classify/src/gtr123_model.py
- prediction/src/algorithms/evaluation/evaluation.py
- prediction/src/algorithms/evaluation/metrics.py
I'm currently adding the possibility to evaluate a classification model based on the LIDC dataset as described in #271. Furthermore, I'm currently benchmarking the model that's implemented at the moment.
Even if I still haven't finished, I wanted to show you what I'm currently working at.
> #271 Classification Evaluation

- docs/design-doc.md
As demanded by #283 this adds a documentation of how to train a segmentation model using the LIDC dataset.
> #283 Document how to train the segmentation model

- prediction/src/algorithms/evaluation/evaluate_detection.py
- prediction/src/algorithms/segment/src/models/simple_3d_model.py
- prediction/src/algorithms/segment/trained_model.py
- prediction/src/preprocess/lung_segmentation.py
- prediction/src/tests/test_volume_calculation.py
Previous behaviour leads to various `memory error`s. It happened time to time 'cause of unreasonably large choice of the [`DATA_SHAPE`](https://github.com/concept-to-clinic/concept-to-clinic/commit/06117fb72b1bf03ad8b522d2f9e42af1b6711a2c#diff-638bbca55ea01b2d5eeb28b7e52321eeR21). The average maximum height of lungs for a grown man, according to [this research](https://www.researchgate.net/profile/Kevin_Capello/publication/221873867_Linear_dimensions_and_volumes_of_human_lungs_obtained_from_CT_images/links/5a1d79daaca2726120b2c4b5/Linear-dimensions-and-volumes-of-human-lungs-obtained-from-CT-images.pdf) (Table 2), is 282mm with std equals to 22mm and median 274mm (Table 2). Assuming normal distribution, [3 sigmas](https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule) aside the …
> Fix memory and styling errors

- prediction/src/algorithms/classify/src/classification_model.py
- prediction/src/algorithms/classify/src/lr3dcnn/model.py
- prediction/src/tests/test_classification.py
- prediction/src/tests/test_classification_3dlrcnn.py
Refactoring of [`evaluate_detection.py`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:refactoring?expand=1#diff-4764e224c7f674ff2dc226aeafcfedb9) and uncommented tests in [`test_classification.py`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:refactoring?expand=1#diff-923cd917610b38983b2ce7907638acc4), as was mentioned in [this](https://github.com/concept-to-clinic/concept-to-clinic/pull/298#pullrequestreview-92612801) comment. Remove redundant [`self.scale_factor`](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/files#diff-7ebde87c389dab64f0c9e8a81e6b6391L40) which is neither dependend on DATA_SHAPE nor on [`self.input_shape`](https://github.com/concept-to-clinic/concept-to-clinic/pull/304/files#diff-7 …
> Reactivate tests and clear models

- compose/base/Dockerfile-dev
Just added `python3-distutils` in the installation packages because of a new requirement of Ubuntu 18.04
https://github.com/concept-to-clinic/concept-to-clinic/issues/312: 
`python3-pip` now requires `python3-distutils` or else it exits with an error.
**Without this change the build fails.**
After the change the stack has been built successfully.
My test environment is Win10 Pro 1803 64Bit with Docker v.18.03.1-ce-win65 (17513) stable.
This should affect all platforms.
> Build was failing at step 5/21 with code 1.

- compose/base/Dockerfile-dev
Installing Python 3.6 in the Docker base image throws an error at  
`RUN add-apt-repository ppa:jonathonf/python-3.6`  
since this repository has been removed. Fortunately, this Ubuntu version already has Python 3.6 installed so we can safely remove this step from the build file [as can be seen here](https://travis-ci.com/WGierke/concept-to-clinic/builds/141771352).
> Remove ppa:jonathonf
