drivendataorg/concept-to-clinic

docs/contribute.md

Fixed the links for open issues and developer documentation in the[ main documentation page](https://concept-to-clinic.readthedocs.io/en/latest/contribute.html#getting-started) 
Fix broken links in main documentation #52  
Fixing broken links in the Getting Started section of the main documentation page.
The updated links are working.

Fixed broken links in the main documentation

---

interface/backend/images/models.py
interface/backend/images/tests.py
interface/requirements/base.txt

Get or create an `ImageSeries` instance given the path to a DICOM directory.
I added the class function `get_or_create` to the `ImageSeries` class.
This should solve #39 
The `ImageSeries` model needs to know the data it's holding.
I wrote a test for it.

#39 Inspect a DICOM directory and create appropriate model instances

---

docs/algorithm_grt123.md

I added an initial documentation of the grt123 algorithm. As soon as I have some specs on how long the prediction takes, I'll replace the TODOs. Please feel free to add commits and extend it!
This pull request addresses #18 .

#18 Document the grt123 algorithm

---

docs/algorithm_hammack.md

I added an initial documentation of the Daniel Hammack algorithm. The algorithm output was ensembled with the results of the [Julian de Wit algorithm](https://github.com/concept-to-clinic/concept-to-clinic/issues/20) whose documentation should follow soon. Please feel free to add commits and extend it!
This pull request addresses #19  .

#19 Document the Daniel Hammack algorithm

---

docs/algorithm_deep_breath.md

An initial version of the documentation for the Deep Breath algorithm. Especially the "Model evaluation" and "Adaptation into Concept to Clinic" sections still need to be improved!
This pull request addresses #27 
The Deep Breath algorithm provides useful insight into the nodule detection/segmentation process, and how the results can be used to make predictions. This documentation should help evaluate the algorithm and its usage for Concept to Clinic.

Documentation of Deep Breath algorithm

---

docs/algorithm_therapixel.md

I added an initial documentation of the Therapixel algorithm. The algorithm scored 5th place during the DSB 2017.
Unfortunately, there is no technical report or blog post about the approach so far.
Thus, I had to derive the algorithm design from the source code and black-box models only, which resulted in a shorter documentation than for other algorithms.
This pull request addresses #23 

#23 Document the Therapixel algorithm

---

.gitattributes
docs/apidoc_prediction/src.algorithms.identify.rst
docs/apidoc_prediction/src.preprocess.rst
docs/apidoc_prediction/src.tests.rst
local.yml
prediction/requirements/base.txt
prediction/src/algorithms/identify/assets/model_luna16_full__fs_best.hd5
prediction/src/algorithms/identify/assets/model_luna_posnegndsb_v1__fs_h0_end.hd5
prediction/src/algorithms/identify/assets/model_luna_posnegndsb_v1__fs_h1_end.hd5
prediction/src/algorithms/identify/assets/model_luna_posnegndsb_v2__fs_h0_end.hd5
prediction/src/algorithms/identify/assets/model_luna_posnegndsb_v2__fs_h1_end.hd5
prediction/src/algorithms/identify/helpers.py
prediction/src/algorithms/identify/prediction.py
prediction/src/algorithms/identify/trained_model.py
prediction/src/algorithms/segment/trained_model.py
prediction/src/preprocess/load_dicom.py
prediction/src/tests/test_endpoints.py
tests/test_docker.sh

I adapted the source code of [Julian de Wit](https://github.com/juliandewit/kaggle_ndsb2017) whose solution scored 2nd pace during the DSB 2017. I decided to use it as it was already written for Python 3, has a manageable code base and immediately ran using my CPU only. The algorithm is documented [here](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/docs/algorithm_de_wit.md). It uses a Conv3D network to detect nodules. The network returns a set of nodules characterized by their position and the probability, that the marked tissue really is a nodule. This output is wrapped into the placeholder function that's already implemented in [prediction/src/algorithms/identify/trained_model/predict](https://github.com/concept-to-clinic/concept-to-clinic/blob/master/prediction/src …

#1 Identify Nodules: Julian de Wit Algorithm

---

docs/algorithm_alex_andre_gilberto_shize.md

This is an initial documentation of the Alex | Andre | Gilberto | Shize algorithm. The team takes the 8th place on the DSB17 private LB. The approach outstands by both: the mosaic data augmentation approach and the notable noodles detection sliding 3D architectures. 
This pull request addresses #26 
This approach allows both nodules detection and segmentation at the same stages, which are into of the current area of interest.

#26 Document the Alex | Andre | Gilberto | Shize algorithm

---

docs/algorithm_DL_Munich.md

An initial version of the documentation for the DL Munich algorithm. The DL Munich team gained the 7th place on the Data Science Bowl 2017 private leaderboard. 
This address #25
the method of nodules segmentation is well generalised and may be integrated with the Alex | Andre | Gilberto | Shize segmentation algorithm.

Documented the DL Munich algorithm

---

docs/algorithm_aidence.md

An initial version of the documentation for the Aidence algorithm. The Aidence team gained the 3rd place on the Data Science Bowl 2017 private leaderboard.
This address #21
>At some point we need to implement an algorithm that can segment the nodules and detect whether they are malicious or not. It makes sense to first evaluate the top 10 solutions for the Data Science Bowl 2017 regarding how performant they are and how easy it would be to use them in our application.

#21 Documented Aidence algorithm

---

docs/developing-locally-docker.md

I added @isms' post to the documentation.
It references issue #153 .

#153 Add how to create JSON data to docs

---

.gitattributes
compose/documentation/Dockerfile-dev
compose/interface/Dockerfile-dev-api
compose/prediction/Dockerfile-dev
prediction/requirements/base.txt
prediction/requirements/local.txt
prediction/requirements/torch.txt
prediction/src/algorithms/classify/__init__.py
prediction/src/algorithms/classify/src/gtr123_model.py
prediction/src/algorithms/classify/trained_model.py
prediction/src/algorithms/identify/__init__.py
prediction/src/algorithms/identify/src/gtr123_model.py
prediction/src/algorithms/identify/trained_model.py
prediction/src/algorithms/segment/__init__.py
prediction/src/algorithms/segment/trained_model.py
prediction/src/factory.py
prediction/src/preprocess/lung_segmentation.py
prediction/src/preprocess/preprocess_ct.py
prediction/src/views.py
requirements.txt

A few fixes and optimizations necessary to make the docker routes functional
After running `docker-compose -f local.yml up` and navigating to `http://0.0.0.0:8001/`, there were several `ImportErrors` that needed fixing. 
The python requirements are quite large. This reduces the amount of data
that needs to be re-downloaded in the case of timeouts or changes to the
requirements files. 
https://www.ctl.io/developers/blog/post/more-docker-image-cache-tips/
Moved ignore filter to bottom of file and consolidated remaining filters.
- `docker-compose -f local.yml up` 
- navigated to `http://0.0.0.0:8000/api/`
- navigated to `http://0.0.0.0:8001/`
- navigated to `http://0.0.0.0:8080/`

Fixes and optimisations to make the docker routes functional

---

prediction/src/algorithms/identify/prediction.py

The `predict_cubes` function has been refactored to reduce its complexity. 
The `predict_cubes` is now splitted on the support functions:
-[`prepare_data`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:166_predict_cubes_refactoring?expand=1#diff-632542ba71c59c64b64a4bc113a8c4b6R148), by a given patient ID it returns three np.ndarray.
-[`annotate`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:166_predict_cubes_refactoring?expand=1#diff-632542ba71c59c64b64a4bc113a8c4b6R229), by a given model and a volumetric data, it returns a DataFrame.
-[`stats_from_batch`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:166_predict_cubes_refactoring?expand=1#diff-632542ba71c59c64b64a4bc113a8c4b6R289), …

#166 Refactored predict cubes

---

docs/algorithm_qfpxfd.md

However qfpxfd algorithm has taken the 4th place in Data Science bowl, its repo's [link](http://www.cis.pku.edu.cn/faculty/vision/wangliwei/software.html) in issue #22 is outdated and http://www.cis.pku.edu.cn is not sustainable either thus it is generally hard to find any information about it. So an investigation took place in order to find any details about the algorithm. The description of it were taken from the [Luna16](https://luna16.grand-challenge.org/results/). The authors were emailed in order to get an actual info. The description will be updated if authors reply.
This is the description of qfpxfd algorithm.  This team gained the 4th place on the Data Science Bowl 2017 private leaderboard. 
This address #22
>At some point, we need to implement an algorithm that can segment the …

#22 Document the qfpxfd algorithm

---

interface/frontend/src/views/ReportAndExport.vue

Implemented mockup under [`ReportAndExport`](https://github.com/concept-to-clinic/concept-to-clinic/compare/master...vessemer:182_RadReport_mockup?expand=1#diff-e715cd99d4fc9baaa867066276d01308) screen over VueJS
This addresses #182

#182 RadReport mockup

---

.gitignore
local.yml
prediction/src/tests/test_classification.py
prediction/src/tests/test_endpoints.py
prediction/src/tests/test_segmentation.py

Misc fixes
- [Add RUN_SLOW_TESTS docker env](https://github.com/concept-to-clinic/concept-to-clinic/commit/75bfa2165b121c3297b70fd58d55f572367384d8)
- [Ignore api doc .rst files](https://github.com/concept-to-clinic/concept-to-clinic/commit/cec33ad8ef35308d07758f3ac7a6f4092f5bdb0b)
- [Increase test coverage](https://github.com/concept-to-clinic/concept-to-clinic/commit/21a1ef4abfb35b53a9eb54bc159e1cfaa8c0f0ea)
- [Fix test names](https://github.com/concept-to-clinic/concept-to-clinic/commit/382f1a2e396877b34ff438b52419f5d1eb9e0467)
- [Remove unnecessary kwarg](https://github.com/concept-to-clinic/concept-to-clinic/commit/7c14801fdfa31ea31a76c8b4eff3bdf2d4f61325)
pushed to travis

Prediction fixes

---

interface/frontend/src/assets/css/project.css
interface/frontend/src/components/open-image/ImageSeries.vue
interface/frontend/src/components/open-image/OpenDICOM.vue
interface/frontend/src/components/open-image/TreeView.vue

At this moment only slide preview was available, this PR allows selecting the desired slice from a list by clicking on its name. 
It also fixes issue #241

Allow to select slice

---

interface/backend/api/views.py
interface/backend/cases/tests.py
prediction/src/tests/test_segmentation.py

Apparently the segmentation issues noted in #229 have been fixed as a byproduct of #237 . This PR just adds the test given in #229 to show that all tests pass.

#229 Fix Segmentation

---

prediction/src/algorithms/segment/src/models/segmentation_model.py
prediction/src/preprocess/lung_segmentation.py

I skimmed through the code and added doc strings to some functions I added whose exact method signatures and purposes I still was able to recap. More exhaustive doc string adding PRs will follow.
#274

#274 Add doc strings

---

prediction/src/tests/test_cropping.py

Added test for changes introduced in PR #273 - (fixed classification prediction for multiple nodules)

Added test for multiple patches cropping

---

prediction/src/preprocess/improved_lung_segmentation.py

Refactoring of lungs separation: `remove_trash`, `if_separate`

Refactoring lungs separation
